[package]
name = "wipe"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Wipe your terminal with a random animation."
repository = "https://github.com/ricoriedel/wipe"

[dependencies]
